### ISSUE TITLE
reindexutxo problem

### ISSUE THREAD

**Issue by cooltya** [SadikSunbul/GO-BlockChain-Simulation#24]
I created a wallet in your project and then I created a blockchain with that wallet. I ran Getbalance to see if I received the block reward. It seems that the blog reward has not been received. When I examine the blocks, the reward should have arrived. The money transfer did not work. Then I ran reindexutxo. Everything was fine, but when the money was transferred, the same problems appeared again. Can you set it to run hot while it's being produced?

**Comment by SadikSunbul** [comment]
Thank you . The problem is solved, you can pull the comit I sent to part-8 and main branches and try again.
