### ISSUE TITLE
Badger DB problem

### ISSUE THREAD

**Issue by cooltya** [SadikSunbul/GO-BlockChain-Simulation#3]
I am getting an error about the badger in part-3 and part-4, it says there is a problem with the logs. What should I do

**Comment by SadikSunbul** [comment]
Delete the tmp/blocks file and then create the block file under tmp. In the project location type "go run main.go -help" first "go run main.go createblockchain -address "pubKey" " Create a blockchain by running this and then you can do the other steps.
